sudo: required
services:
  - docker

before_install:
  - docker build -t dragossusman/frontend -f Dockerfile.dev .

script:
  - docker run dragossusman/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-us-east-2-673556973170"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_USER"
  secret_access_key: "$AWS_ACCESS_PWD"